SinExWebApp20256966/SinExWebApp20256966/Models/Shipment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SinExWebApp20256966.Models
{
    [Table("Shipment")]
    public class Shipment
    {
        [Key]
        public virtual int WaybillId { get; set; }
        [StringLength(10)]
        [RegularExpression(@"^[A-za-z0-9]*$", ErrorMessage = "The reference number must be alphanumeric.")]
        public virtual string ReferenceNumber { get; set; }
        [Required]
        public virtual string ServiceType { get; set; }
        [DataType(DataType.Date)]
        public virtual DateTime ShippedDate { get; set; }
        [DataType(DataType.Date)]
        public virtual DateTime DeliveredDate { get; set; }
        [Required]
        [StringLength(35)]
        [RegularExpression(@"^[A-Za-z ,.'-]*$", ErrorMessage = "Your input contains invalid characters.")]
        public virtual string RecipientName { get; set; }
        public virtual int NumberOfPackages { get; set; }
        public virtual string Origin { get; set; }
        public virtual string Destination { get; set; }
        public virtual string Status { get; set; }  // final status(delivered, returned or lost)
        [Required]
        public virtual int ShippingAccountId { get; set; }




        //New Attributes for A3

        /*For Creation*/

        //Recipient Information
        public virtual string CompanyName { get; set; }
        public virtual string DepartmentName { get; set; }
        //Delivery Address
        public virtual string Building { get; set; }
        public virtual string Street { get; set; }
        public virtual string City { get; set; }
        public virtual string Province { get; set; }
        public virtual string PostalCode { get; set; }
        [Required]
        public virtual string PhoneNumber { get; set; }
        [Required]
        public virtual string EmailAddress { get; set; }

        //Shipment Information
        public virtual ICollection<Package> Packages { get; set; }
        [Required]
        public virtual int ShipmentPayerID { get; set; }
        [Required]
        public virtual int DutiesTaxesPayerID { get; set; }
        public virtual string ShipmentCurrency { get; set; }
        public virtual string DutiesTaxesCurrency { get; set; }

        //Email Notification
        [Required]
        public virtual bool NotifySender { get; set; }
        [Required]
        public virtual bool NotifyRecipient { get; set; }

        /*For Confirmation*/
        public virtual bool ConfirmStatus { get; set; }
        public virtual string PickupType { get; set; }
        [DataType(DataType.DateTime)]
        public virtual DateTime? PickupTime { get; set; }
        public virtual string PickupLocation { get; set; }

        /*For Deletion*/
        public virtual bool DeleteStatus { get; set; }
        public virtual bool PickupStatus { get; set; }

        /*For Payment(feedback)*/
        public virtual string ShipemtnPaymentAuthorizationCode { get; set; }
        public virtual string DutiesTaxesPaymentAuthorizationCode { get; set; }

        // Cost of whole shipment, duty and tax
        public virtual double? ShipmentAmount { get; set; }
        public virtual double? DutiesAmount { get; set; }
        public virtual double? TaxesAmount { get; set; }

        // Total invoice amount, used only in generate invoice history if there is only one payer
        public virtual double? TotalInvoiceAmount { get; set; }

        // shipment tracking
        public virtual ICollection<ShipmentTracking> ShipmentTrackingInformation { get; set; }
    }
}

SinExWebApp20256966/SinExWebApp20256966/ViewModels/EmployeeEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
using SinExWebApp20256966.Models;

namespace SinExWebApp20256966.ViewModels
{
    public class EmployeeEditViewModel
    {
        public virtual string waybillId { get; set; }
        public virtual string ServiceType { get; set; }
        public virtual string RecipientName { get; set; }
        public virtual string Building { get; set; }
        public virtual string Street { get; set; }
        public virtual string City { get; set; }
        public virtual string Province { get; set; }
        public virtual string PostalCode { get; set; }
        public virtual string PhoneNumber { get; set; }
        public virtual string EmailAddress { get; set; }
        public virtual List<Package> Packages { get; set; }
        public virtual double? DutiesAmount { get; set; }
        public virtual double? TaxesAmount { get; set; }

        public virtual List<double?> ActualWeight { get; set; }
    }
}

SinExWebApp20256966/SinExWebApp20256966/Controllers/ShipmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20256966.Models;
using SinExWebApp20256966.ViewModels;
using X.PagedList;
using System.Text.RegularExpressions;

// Add spaces to allow use of the mail sending functionality.
using System.Net.Mail;
using System.Web.UI.WebControls;
using System.Collections.Specialized;

namespace SinExWebApp20256966.Controllers
{
    //[Authorize(Roles ="Customer, Employee")]
    public class ShipmentsController : Controller
    {
        private SinExWebDatabaseContext db = new SinExWebDatabaseContext();

        [Authorize(Roles = "Customer")]
        // new CREATE
        public ActionResult CreateShipment(string ReferenceNumber, string OriginCity, string RecipientName, string CompanyName, string DepartmentName, string UseSavedAddress, string RecipientAddressNickName, string Building, string Street, string City, string PostalCode, string PhoneNumber, string EmailAddress, string ServiceType, string ShipmentPayer, string DutiesTaxesPayer, string RecipientAccountNumber, string NotifySender, string NotifyRecipient, int? PackageNumber, List<string> TypeSizes, List<string> ContentDescriptions, List<string> CustomerWeights, List<string> Values, List<string> Currencies, string submit)
        {
            var shipmentcreate = new CreateShipmentViewModel();
            string username = System.Web.HttpContext.Current.User.Identity.Name;
            ShippingAccount account = db.ShippingAccounts.SingleOrDefault(s => s.UserName == username);

            string message = "";

            var typesize = new SelectList(db.PackageTypeSizes.OrderBy(c => c.PackageTypeID).Select(c => c.Size).Distinct());
            var currency = new SelectList(db.Currencies.OrderBy(c => c.CurrencyCode).Select(c => c.CurrencyCode).Distinct());
            shipmentcreate.TypeSizeList = typesize.ToList();
            shipmentcreate.CurrencyList = currency.ToList();

            var origincity = new SelectList(db.Destinations.OrderBy(c => c.City).Select(c => c.City).Distinct());
            var usesavedaddress = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Yes", Value = "Yes"},
                new SelectListItem { Text = "No", Value = "No"},
            }, "Value", "Text");
            var recipientaddressnickname = new SelectList(db.RecipientAddresses.Where(s => s.ShippingAccountId == account.ShippingAccountId).Select(s => s.NickName).Distinct());
            var servicetype = new SelectList(db.ServiceTypes.OrderBy(c => c.ServiceTypeID).Select(c => c.Type).Distinct());
            var city = new SelectList(db.Destinations.OrderBy(c => c.City).Select(c => c.City).Distinct());
            var shipmentpayer = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Sender", Value = "Sender"},
                new SelectListItem { Text = "Recipient", Value = "Recipient"},
            }, "Value", "Text");
            var dutiestaxespayer = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Sender", Value = "Sender"},
                new SelectListItem { Text = "Recipient", Value = "Recipient"},
            }, "Value", "Text");
            var notifysender = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Yes", Value = "Yes"},
                new SelectListItem { Text = "No", Value = "No"},
            }, "Value", "Text");
            var notifyrecipient = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "Yes", Value = "Yes"},
                new SelectListItem { Text = "No", Value = "No"},
            }, "Value", "Text");


            ShippingAccount person = db.ShippingAccounts.SingleOrDefault(c => c.UserName == User.Identity.Name);
            if (person is BusinessShippingAccount)
            {
                ViewBag.AccountType = "BusinessShippingAccount";
                BusinessShippingAccount bperson = (BusinessShippingAccount)db.ShippingAccounts.SingleOrDefault(c => c.UserName == User.Identity.Name);
                ViewBag.FullName = bperson.ContactPersonName + " " + bperson.CompanyName;
            }
            else if (person is PersonalShippingAccount)
            {
                ViewBag.AccountType = "PersonalShippingAccount";
                PersonalShippingAccount pperson = (PersonalShippingAccount)db.ShippingAccounts.SingleOrDefault(c => c.UserName == User.Identity.Name);
                ViewBag.FullName = pperson.FirstName + " " + pperson.LastName;
            }
            ViewBag.AccountNo = account.ShippingAccountId.ToString("000000000000");
            ViewBag.MailingAddress = account.AddressBuilding + " " + account.AddressStreet + " " + account.AddressCity + " " + account.AddressProvinceCode;
            ViewBag.PhoneNumber = account.PhoneNumber;
            ViewBag.EmailAddress = account.Email;
            ViewBag.OriginCity = origincity.ToList();

            if (PackageNumber == null)
            {
                ViewBag.packagenumber = 1;
            }
            else
            {
                ViewBag.packagenumber = (int)PackageNumber;
            }
            if (submit == "Add a package")
            {
                ViewBag.packagenumber = (int)PackageNumber + 1;
            }
            if (submit == "Delete a package")
            {
                ViewBag.packagenumber = (int)PackageNumber - 1;
            }

            ViewBag.UseSavedAddress = usesavedaddress.ToList();
            ViewBag.RecipientAddressNickName = recipientaddressnickname.ToList();
            ViewBag.ServiceType = servicetype.ToList();
            ViewBag.City = city.ToList();
            ViewBag.ShipmentPayer = shipmentpayer.ToList();
            ViewBag.DutiesTaxesPayer = dutiestaxespayer.ToList();
            ViewBag.NotifySender = notifysender.ToList();
            ViewBag.NotifyRecipient = notifyrecipient.ToList();



            if (submit == "Create")
            {
                // Recipient Information
                string Province = "";
                if (UseSavedAddress == "Yes")
                {
                    if (String.IsNullOrEmpty(RecipientAddressNickName))
                    {
                        message = "Pleasse select a saved recipient address";
                        ViewBag.message = message;
                        return View(shipmentcreate);
                    }
                    else
                    {
                        var addressinfo = db.RecipientAddresses.Where(s => s.ShippingAccountId == account.ShippingAccountId).Where(s => s.NickName == RecipientAddressNickName).Single();
                        Building = addressinfo.Building;
                        Street = addressinfo.Street;
                        City = addressinfo.City;
                        Province = addressinfo.Province;
                        PostalCode = addressinfo.PostalCode;
                    }
                }
                else
                {
                    if (String.IsNullOrEmpty(Street) || String.IsNullOrEmpty(City))
                    {
                        message = "Pleasse input or select Street and City  for delivery purpose.";
                        ViewBag.message = message;
                        return View(shipmentcreate);
                    } else
                    {
                        Province = db.Destinations.Where(s => s.City == City).Select(s => s.ProvinceCode).Single();
                        var pc = db.Destinations.SingleOrDefault(c => c.City == City).ProvinceCode;
                        //int ProvincePostalMatch = 0;
                        //string ReResult = Regex.Match(PostalCode, @"^[0-9][0-9]").Value;
                        //string ReResult_TW = Regex.Match(PostalCode, @"^[1-9][0-9][0-9]").Value;

                        int ProvincePostalMatch = 0;
                        if (!String.IsNullOrEmpty(PostalCode)) {
                            ProvincePostalMatch = ProvincePostalMatchFunc(pc, PostalCode);
                        }
                        else
                        {
                            ProvincePostalMatch = 1;
                        }

                        if (ProvincePostalMatch == 0)
                        {
                            message = "The City and PostalCode do not match, please check it carefully.";
                            ViewBag.message = message;
                            return View(shipmentcreate);
                        }
                    }
                }

                // Payer
                if (ShipmentPayer == "Recipient" || DutiesTaxesPayer == "Recipient")
                {
                    if (String.IsNullOrEmpty(RecipientAccountNumber))
                    {
                        message = "Pleasse input the Account Number of recipient";
                        ViewBag.message = message;
                        return View(shipmentcreate);
                    }
                    int accountNum = Convert.ToInt32(RecipientAccountNumber);
                    int recnum = Convert.ToInt32(RecipientAccountNumber);
                    if (db.ShippingAccounts.Where(s => s.ShippingAccountId == recnum).Count() != 1)
                    {
                        message = "Pleasse input a valid Account Number of recipient";
                        ViewBag.message = message;
                        return View(shipmentcreate);
                    }
                }
                int ShipmentPayerID = 0, DutiesTaxesPayerID = 0;
                if (ShipmentPayer == "Recipient")
                {
                    ShipmentPayerID = Convert.ToInt32(RecipientAccountNumber);
                }
                else
                {

SinExWebApp20256966/SinExWebApp20256966/Views/Shipments/Confirm.cshtml
@model SinExWebApp20256966.ViewModels.ShipmentConfirmationViewModel

@{
    ViewBag.Title = "Confirm";
}

<script>
    function myfunction() {
        var x = document.getElementById("PickUpType");
        var y = document.getElementById("date");

        if (x.options[x.selectedIndex].value == "immediate") {
            y.style.display = "none";
        }
        if (x.options[x.selectedIndex].value == "prearranged") {
            y.style.display = "";
        }
    }

    function fun() {
        var y = document.getElementById("locate");
        var x = document.getElementById("PickUpLocationNickname");
        
        if (x.options[x.selectedIndex].value != "") {
            y.style.display = "none";
        }
        else {
            y.style.display = "";
        }
        
    }
</script>



<h2>Confirm</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.PickupLocationNickname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PickUpLocationNickname", null, "Please Select:", htmlAttributes: new { @class = "form-control", @onmouseout = "fun()" })
                @Html.ValidationMessageFor(model => model.PickupLocationNickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" id="locate" >
            @Html.LabelFor(model => model.NewPickupLocation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NewPickupLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewPickupLocation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PickupType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PickUpType", null, "Please Select:", htmlAttributes: new { @class = "form-control", @onmouseout = "myfunction()" })
                @Html.ValidationMessageFor(model => model.PickupType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="date" style="display:none">
            <div class="form-group">
                @Html.LabelFor(model => model.PickupDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PickupDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PickupDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PickupTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PickupTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PickupTime, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Confirm" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}

@{
    string msg = ViewBag.message;
}

@msg

SinExWebApp20256966/SinExWebApp20256966/Views/Shipments/Details.cshtml
@model SinExWebApp20256966.Models.Shipment

@{
    ViewBag.Title = "Shipment Details";
}

<h4>Shipment Details</h4>

<div>
    <hr />
    
    <h4><strong><u>Shipment Information</u></strong></h4>
    <br />
    <dl class="dl-horizontal">
        @{
            var s1 = "Sender user name: ";
            var s2 = "Service Type: ";
            var ss = "Waybill Number: ";
            var refer = "Reference Number: ";
        }
        <dt>
            @refer
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>
        <dt>
            @s2
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ServiceType)
        </dd>
        <dt>
            @ss
        </dt>
        <dd>
            @ViewBag.waybill
        </dd>
    </dl>
    <br />
   

    <div>
        <h4><strong><u>Sender Information</u></strong></h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @s1
            </dt>
            <dd>
                @ViewBag.username
            </dd>
            <dt>
                @Html.DisplayName("AccountNo")
            </dt>
            <dd>
                @Html.Display("AccountNo")
            </dd>

            <dt>
                @Html.DisplayName("FullName")
            </dt>
            <dd>
                @Html.Display("FullName")
            </dd>

            <dt>
                @Html.DisplayName("MailingAddress")
            </dt>
            <dd>
                @Html.Display("MailingAddress")
            </dd>

            <dt>
                @Html.DisplayName("PhoneNumber")
            </dt>
            <dd>
                @Html.Display("PhoneNumber")
            </dd>

            <dt>
                @Html.DisplayName("EmailAddress")
            </dt>
            <dd>
                @Html.Display("EmailAddress")
            </dd>
        </dl>
    </div>
    <br />

    <h4><strong><u>Recipient Information</u></strong></h4>
    <br />
    <dl class="dl-horizontal">
        @{ 
            var s3 = "Name: ";
            var s4 = "Building: ";
            var s5 = "Street: ";
            var s6 = "City: ";
            var s7 = "Province: ";
            var s8 = "Postal code: ";
            var s9 = "Telephone: ";
            var s10 = "Email: ";
        }
        <dt>
            @s3
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecipientName)
        </dd>
        <dt>
            @s4
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Building)
        </dd>
        <dt>
            @s5
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @s6
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @s7
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt>
            @s8
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @s9
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd> 
        <dt>
            @s10
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
    </dl>
    <br />

    <h4><strong><u>Package Information</u></strong></h4>
    <br />
    @{ 
        var p1 = "Type";
        var p2 = "Description";
        var p3 = "Value";
        var h4 = "Customer Weight";
        var p5 = "Actual Weight";
    }   
    
    <div>
        <table class="table">
            <tr>
                <th>@p1</th>
                <th>@p2</th>
                <th>@p3</th>
                <th>@h4</th>
                <th>@p5</th>
                <th>@ViewBag.costmsg</th>
                <th>@ViewBag.actualcostmsg</th>
                <th></th>
            </tr>
            @{ 
                var num = 0;
                double cos = 0;
                double actualcos = 0;
            }
            
            
            @foreach (var item in ViewBag.Packageslist)
            {
                if (item.WaybillId == Model.WaybillId)
                {
                    string val = item.Currency + " " + Convert.ToString(item.Value);
                    cos = ViewBag.packagecost[num];
                    actualcos = ViewBag.actualpackagecost[num];
                    num = num + 1;
                    string vall = ViewBag.currency + " " + cos;
                    string val3 = ViewBag.currency + " " + actualcos;

                <tr>
                    <td>@item.TypeSize</td>
                    <td>@item.ContentDescription</td>
                    <td>@val</td>
                    @if (item.CustomerWeight != 0)
                    {
                        <td>@item.CustomerWeight</td>
                    }
                    else
                    {
                        <td><span>N/A</span></td>
                    }
                    @if (item.ActualWeight != 0)
                    {
                        <td>@item.ActualWeight</td>
                    }
                    else
                    {
                        <td><span>N/A</span></td>
                    }
                    <td>@vall</td>
                    @if (actualcos == 0)
                    {
                        <td>N/A</td>
                    }
                    else
                    {
                        <td>@val3</td>
                    }
                    
                    <td>
                </tr>
                }
            }

        </table>
    </div>
    <br />

    <h4><strong><u>Payer Information</u></strong></h4>
    <br />
    <dl class="dl-horizontal">
    @{ 
        var aa = "Shipment: ";
        var bb = "Duties & Taxes: ";
    }    
        <dt>
            @aa
        </dt>
        <dd>
            @ViewBag.shipmentpayer
        </dd>
        <dt>
            @bb
        </dt>
        <dd>
            @ViewBag.dutypayer
        </dd>
    
    </dl>
    <br />

    <h4><strong><u>Notification Information</u></strong></h4>
    <br />
    <dl class="dl-horizontal">
        @{ 
            var n1 = "Notify sender: ";
            var n2 = "Notify recipient: ";
        }
        <dt>
            @n1
        </dt>

        @if (ViewBag.NotifySender == true)
            {
            <dd>Yes</dd> }
            else
            {
            <dd>No</dd> }

        <dt>
            @n2
        </dt>


        @if (ViewBag.NotifyRecipient == true)
            {
            <dd>Yes</dd> }
            else
            {
            <dd>No</dd> } 
    
    </dl>
    <br />
    <h4><strong><u>Payment Information</u></strong></h4>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @ViewBag.costmsg
        </dt>
        <dd>
            @ViewBag.currency  @ViewBag.shipmentcost
        </dd>   
        <dt>
            @ViewBag.actualcostmsg
        </dt>
        <dd>
            @if (ViewBag.actualshipmentcost > 0)
            {
                @ViewBag.currency @ViewBag.acutalshipmentcost
            }
            else
            {
               <p>N\A</p>
            }
        </dd>   
    </dl>
    
</div>

SinExWebApp20256966/SinExWebApp20256966/Views/Shipments/GenerateHistoryReport.cshtml
@model SinExWebApp20256966.ViewModels.ShipmentsReportViewModel

@{
    ViewBag.Title = "Shipment History";
}
<h2>Shipment History</h2>

@Html.Partial("_ShipmentsSearchPartial", Model.Shipment)
@Html.Partial("_ShipmentsListPartial", Model.Shipments)
@Html.Partial("_ShipmentsPagingPartial", Model.Shipments)

@if (ViewBag.errmsg != null)
{
    @ViewBag.errmsg
}

SinExWebApp20256966/SinExWebApp20256966/Views/Shipments/GenerateInvoiceReport.cshtml
@model SinExWebApp20256966.ViewModels.ShipmentsReportViewModel

@{
    ViewBag.Title = "Invoice History";
}
<h2>Invoice History</h2>

@Html.Partial("_InvoicesSearchPartial", Model.Shipment)
@Html.Partial("_InvoicesListPartial", Model.Shipments)
@Html.Partial("_InvoicesPagingPartial", Model.Shipments)

SinExWebApp20256966/SinExWebApp20256966/Views/Shipments/Index.cshtml
@model IEnumerable<SinExWebApp20256966.Models.Shipment>

@{
    ViewBag.Title = "Shipments Management";
}

<h2>Shipment Management</h2>

@{
    if (User.IsInRole("Customer"))
    {
        <p>
            @Html.ActionLink("Create New", "CreateShipment")
        </p>
    }
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ServiceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeliveredDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecipientName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPackages)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Origin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Destination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ReferenceNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ServiceType)
        </td>
        @if (item.ShippedDate != new DateTime(2000,01,01))
        {
            <td>
                @Html.DisplayFor(modelItem => item.ShippedDate)
            </td>
        }
        else
        {
            <td>  </td>
        }
        @if (item.DeliveredDate != new DateTime(2000, 01, 01))
        {
            <td>
                @Html.DisplayFor(modelItem => item.DeliveredDate)
            </td>
        }
        else
        {
            <td>  </td>
        }
        <td>
            @Html.DisplayFor(modelItem => item.RecipientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfPackages)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Origin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Destination)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.WaybillId })
            @if (item.ConfirmStatus == false && User.IsInRole("Customer"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.WaybillId })
                <br />
                @Html.ActionLink("Confirm", "Confirm", new { id = item.WaybillId })
            }
            @if (item.PickupStatus == false && User.IsInRole("Customer"))
            {
                @Html.ActionLink("Delete", "Delete", new { id = item.WaybillId })
            }
           
        </td>
    </tr>
}

</table>

<p>Notice that for Shipped Date, it will display when the shipment is picked up and updated from the shipment tracking system.</p>

SinExWebApp20256966/SinExWebApp20256966/Views/Shipments/_ShipmentsSearchPartial.cshtml
@model SinExWebApp20256966.ViewModels.ShipmentsSearchViewModel

@using (Html.BeginForm("GenerateHistoryReport", "Shipments", FormMethod.Get))
{

    if ((User.IsInRole("Employee")))
    {
        foreach (var item in Model.ShippingAccounts)
        {
            string s = item.Text;
            string a = Convert.ToInt32(s).ToString("000000000000");
            item.Text = a;
        }

        @Html.LabelFor(a => a.ShippingAccountId, "Shipping Account:")
        @Html.DropDownListFor(a => a.ShippingAccountId, Model.ShippingAccounts, "Please select")
        <input type="submit" value="Search"/>
        @Html.LabelFor(a => a.ShippedStartDates, "Shipped Start Date:")
        @Html.EditorFor(a => a.ShippedStartDate, "Please select")
        @Html.LabelFor(a => a.ShippedEndDates, "Shipped End Date:")
        @Html.EditorFor(a => a.ShippedEndDate, "Please select")
        <input type="submit" value="Search" />
    }
    else
    {
        @Html.LabelFor(a => a.ShippedStartDates, "Shipped Start Date:")
        @Html.EditorFor(a => a.ShippedStartDate, "Please select")
        @Html.LabelFor(a => a.ShippedEndDates, "Shipped End Date:")
        @Html.EditorFor(a => a.ShippedEndDate, "Please select")
        <input type="submit" value="Search" />
    }

}